apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: utilize-aws
  region: ap-northeast-1
  version: '1.21'
  tags:
    Purpose: LearnEKS

iam:
  withOIDC: true
  serviceAccounts: []

availabilityZones:
  - ap-northeast-1a
  - ap-northeast-1c
  - ap-northeast-1d

managedNodeGroups:
  - name: basic-ng
    instanceType: c5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 16
    volumeType: gp3
    privateNetworking: true
    tags:
      Purpose: LearnEKS

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
